component_depth: 1
languages:
- java 
exclude:
- ./META-INF/.*
- ./bin/.*
- ./bin/com/.*
- ./bin/com/jgraph/.*
- ./bin/com/jgraph/algebra/.*
- ./bin/com/jgraph/algebra/cost/.*
- ./bin/com/jgraph/components/.*
- ./bin/com/jgraph/components/labels/.*
- ./bin/com/jgraph/example/.*
- ./bin/com/jgraph/example/adapter/.*
- ./bin/com/jgraph/example/adapter/image/.*
- ./bin/com/jgraph/example/fastgraph/.*
- ./bin/com/jgraph/example/groupeditor/.*
- ./bin/com/jgraph/example/mycellmodeleditor/.*
- ./bin/com/jgraph/example/mycellview/.*
- ./bin/com/jgraph/example/panelexample/.*
- ./bin/com/jgraph/example/portlabels/.*
- ./bin/com/jgraph/io/.*
- ./bin/com/jgraph/io/svg/.*
- ./bin/com/jgraph/layout/.*
- ./bin/com/jgraph/layout/demo/.*
- ./bin/com/jgraph/layout/graph/.*
- ./bin/com/jgraph/layout/hierarchical/.*
- ./bin/com/jgraph/layout/hierarchical/model/.*
- ./bin/com/jgraph/layout/image/.*
- ./bin/com/jgraph/layout/organic/.*
- ./bin/com/jgraph/layout/routing/.*
- ./bin/com/jgraph/layout/simple/.*
- ./bin/com/jgraph/layout/svg/.*
- ./bin/com/jgraph/layout/tree/.*
- ./bin/com/jgraph/navigation/.*
- ./bin/com/jgraph/util/.*
- ./bin/org/.*
- ./bin/org/jgraph/.*
- ./bin/org/jgraph/event/.*
- ./bin/org/jgraph/example/.*
- ./bin/org/jgraph/graph/.*
- ./bin/org/jgraph/plaf/.*
- ./bin/org/jgraph/plaf/basic/.*
- ./bin/org/jgraph/util/.*
- ./doc/.*
- ./doc/api/.*
- ./doc/api/com/.*
- ./doc/api/com/jgraph/.*
- ./doc/api/com/jgraph/algebra/.*
- ./doc/api/com/jgraph/algebra/class-use/.*
- ./doc/api/com/jgraph/algebra/cost/.*
- ./doc/api/com/jgraph/algebra/cost/class-use/.*
- ./doc/api/com/jgraph/components/.*
- ./doc/api/com/jgraph/components/labels/.*
- ./doc/api/com/jgraph/components/labels/class-use/.*
- ./doc/api/com/jgraph/io/.*
- ./doc/api/com/jgraph/io/svg/.*
- ./doc/api/com/jgraph/io/svg/class-use/.*
- ./doc/api/com/jgraph/layout/.*
- ./doc/api/com/jgraph/layout/class-use/.*
- ./doc/api/com/jgraph/layout/graph/.*
- ./doc/api/com/jgraph/layout/graph/class-use/.*
- ./doc/api/com/jgraph/layout/hierarchical/.*
- ./doc/api/com/jgraph/layout/hierarchical/class-use/.*
- ./doc/api/com/jgraph/layout/hierarchical/model/.*
- ./doc/api/com/jgraph/layout/hierarchical/model/class-use/.*
- ./doc/api/com/jgraph/layout/organic/.*
- ./doc/api/com/jgraph/layout/organic/class-use/.*
- ./doc/api/com/jgraph/layout/routing/.*
- ./doc/api/com/jgraph/layout/routing/class-use/.*
- ./doc/api/com/jgraph/layout/simple/.*
- ./doc/api/com/jgraph/layout/simple/class-use/.*
- ./doc/api/com/jgraph/layout/tree/.*
- ./doc/api/com/jgraph/layout/tree/class-use/.*
- ./doc/api/com/jgraph/navigation/.*
- ./doc/api/com/jgraph/navigation/class-use/.*
- ./doc/api/com/jgraph/util/.*
- ./doc/api/com/jgraph/util/class-use/.*
- ./doc/api/org/.*
- ./doc/api/org/jgraph/.*
- ./doc/api/org/jgraph/class-use/.*
- ./doc/api/org/jgraph/event/.*
- ./doc/api/org/jgraph/event/class-use/.*
- ./doc/api/org/jgraph/graph/.*
- ./doc/api/org/jgraph/graph/class-use/.*
- ./doc/api/org/jgraph/plaf/.*
- ./doc/api/org/jgraph/plaf/basic/.*
- ./doc/api/org/jgraph/plaf/basic/class-use/.*
- ./doc/api/org/jgraph/plaf/class-use/.*
- ./doc/api/org/jgraph/util/.*
- ./doc/api/org/jgraph/util/class-use/.*
- ./examples/.*
- ./examples/com/.*
- ./examples/com/jgraph/.*
- ./examples/com/jgraph/components/.*
- ./examples/com/jgraph/example/.*
- ./examples/com/jgraph/example/adapter/.*
- ./examples/com/jgraph/example/adapter/image/.*
- ./examples/com/jgraph/example/fastgraph/.*
- ./examples/com/jgraph/example/groupeditor/.*
- ./examples/com/jgraph/example/mycellmodeleditor/.*
- ./examples/com/jgraph/example/mycellview/.*
- ./examples/com/jgraph/example/panelexample/.*
- ./examples/com/jgraph/example/portlabels/.*
- ./examples/com/jgraph/layout/.*
- ./examples/com/jgraph/layout/demo/.*
- ./examples/com/jgraph/layout/image/.*
- ./examples/com/jgraph/layout/svg/.*
- ./examples/com/jgraph/navigation/.*
- ./examples/org/.*
- ./examples/org/jgraph/.*
- ./examples/org/jgraph/example/.*
- ./lib/.*
